// sample code

const int loudspeaker_pin = 13;
const int base_time = 16 * 50; // 16の倍数が都合がいい

void setup()
{
  pinMode( loudspeaker_pin, OUTPUT);
}

void loop()
{
  tone(loudspeaker_pin, 880);
  delay(base_time * 3 / 2 / 4);
  tone(loudspeaker_pin, 880);
  delay(base_time / 1);
  tone(loudspeaker_pin, 880);
  delay(base_time / 1);
  tone(loudspeaker_pin, 740);
  delay(base_time / 1);
  tone(loudspeaker_pin, 587);
  delay(base_time / 2);
  tone(loudspeaker_pin, 587);
  delay(base_time / 1);
  tone(loudspeaker_pin, 587);
  delay(base_time / 1);
  tone(loudspeaker_pin, 659);
  delay(base_time / 1);
  tone(loudspeaker_pin, 740);
  delay(base_time / 2);
  tone(loudspeaker_pin, 740);
  delay(base_time / 1);
  tone(loudspeaker_pin, 659);
  delay(base_time / 1);
  tone(loudspeaker_pin, 587);
  delay(base_time / 1);
  tone(loudspeaker_pin, 659);
  delay(base_time / 4);
  tone(loudspeaker_pin, 740);
  delay(base_time * 3 / 2 / 2);
  tone(loudspeaker_pin, 784);
  delay(base_time / 1);
  tone(loudspeaker_pin, 880);
  delay(base_time / 1);
  tone(loudspeaker_pin, 988);
  delay(base_time / 1);
  tone(loudspeaker_pin, 880);
  delay(base_time / 2);
  tone(loudspeaker_pin, 880);
  delay(base_time / 1);
  tone(loudspeaker_pin, 880);
  delay(base_time / 1);
  tone(loudspeaker_pin, 740);
  delay(base_time / 1);
  tone(loudspeaker_pin, 659);
  delay(base_time / 2);
  tone(loudspeaker_pin, 659);
  delay(base_time / 1);
  tone(loudspeaker_pin, 587);
  delay(base_time / 1);
  tone(loudspeaker_pin, 659);
  delay(base_time / 1);
  tone(loudspeaker_pin, 740);
  delay(base_time / 4);
  tone(loudspeaker_pin, 740);
  delay(base_time / 16);
  tone(loudspeaker_pin, 880);
  delay(base_time / 1);
  tone(loudspeaker_pin, 1175);
  delay(base_time / 1);
  tone(loudspeaker_pin, 1175);
  delay(base_time / 2);
  tone(loudspeaker_pin, 880);
  delay(base_time / 1);
  tone(loudspeaker_pin, 740);
  delay(base_time / 1);
  tone(loudspeaker_pin, 880);
  delay(base_time / 1);
  tone(loudspeaker_pin, 880);
  delay(base_time / 2);
  tone(loudspeaker_pin, 740);
  delay(base_time / 1);
  tone(loudspeaker_pin, 587);
  delay(base_time / 1);
  tone(loudspeaker_pin, 740);
  delay(base_time / 1);
  tone(loudspeaker_pin, 740);
  delay(base_time * 3 / 2 / 2);
  tone(loudspeaker_pin, 659);
  delay(base_time / 1);
  tone(loudspeaker_pin, 587);
  delay(base_time / 4);
  tone(loudspeaker_pin, 880);
  delay(base_time / 4);
  tone(loudspeaker_pin, 880);
  delay(base_time / 4);
  tone(loudspeaker_pin, 880);
  delay(base_time / 4);
  tone(loudspeaker_pin, 698);
  delay(base_time / 4);
  tone(loudspeaker_pin, 587);
  delay(base_time / 4);
  tone(loudspeaker_pin, 587);
  delay(base_time / 4);
  tone(loudspeaker_pin, 587);
  delay(base_time / 4);
  tone(loudspeaker_pin, 659);
  delay(base_time / 4);
  tone(loudspeaker_pin, 698);
  delay(base_time / 4);
  tone(loudspeaker_pin, 698);
  delay(base_time / 4);
  tone(loudspeaker_pin, 659);
  delay(base_time / 4);
  tone(loudspeaker_pin, 587);
  delay(base_time / 4);
  tone(loudspeaker_pin, 659);
  delay(base_time / 4);
  tone(loudspeaker_pin, 698);
  delay(base_time / 4);
  tone(loudspeaker_pin, 784);
  delay(base_time / 4);
  tone(loudspeaker_pin, 880);
  delay(base_time / 4);
  tone(loudspeaker_pin, 988);
  delay(base_time / 4);
  tone(loudspeaker_pin, 880);
  delay(base_time / 4);
  tone(loudspeaker_pin, 880);
  delay(base_time / 4);
  tone(loudspeaker_pin, 880);
  delay(base_time / 4);
  tone(loudspeaker_pin, 698);
  delay(base_time / 4);
  tone(loudspeaker_pin, 659);
  delay(base_time / 4);
  tone(loudspeaker_pin, 659);
  delay(base_time / 4);
  tone(loudspeaker_pin, 587);
  delay(base_time / 4);
  tone(loudspeaker_pin, 659);
  delay(base_time / 4);
  tone(loudspeaker_pin, 698);
  delay(base_time / 4);
  tone(loudspeaker_pin, 698);
  delay(base_time / 4);
  tone(loudspeaker_pin, 880);
  delay(base_time / 4);
  tone(loudspeaker_pin, 1175);
  delay(base_time / 4);
  tone(loudspeaker_pin, 1175);
  delay(base_time / 4);
  tone(loudspeaker_pin, 880);
  delay(base_time / 4);
  tone(loudspeaker_pin, 698);
  delay(base_time / 4);
  tone(loudspeaker_pin, 880);
  delay(base_time / 4);
  tone(loudspeaker_pin, 880);
  delay(base_time / 4);
  tone(loudspeaker_pin, 698);
  delay(base_time / 4);
  tone(loudspeaker_pin, 587);
  delay(base_time / 4);
  tone(loudspeaker_pin, 698);
  delay(base_time / 4);
  tone(loudspeaker_pin, 698);
  delay(base_time / 4);
  tone(loudspeaker_pin, 659);
  delay(base_time / 4);
  tone(loudspeaker_pin, 587);
  delay(base_time / 4);
}

